### ISSUE TITLE
basic cli usage broken

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/cinnabar#70]
Not sure how long this hasn't worked, but running the cli entrypoint with the given example csv doesn't work

```bash
>>> cinnabar ./example.csv 
Traceback (most recent call last):
  File "/home/richard/miniconda3/envs/openfe/bin/cinnabar", line 33, in <module>
    sys.exit(load_entry_point('cinnabar', 'console_scripts', 'cinnabar')())
  File "/home/richard/code/cinnabar/cinnabar/arsenic.py", line 44, in main
    plotting.plot_DDGs(network.results, title=args.title, filename=f"{args.prefix}DDGs.png")
  File "/home/richard/code/cinnabar/cinnabar/plotting.py", line 252, in plot_DDGs
    x = [x[2]["exp_DDG"] for x in graph.edges(data=True)]
AttributeError: 'dict' object has no attribute 'edges'
```

**Comment by richardjgowers** [comment]
fixed in #69
